### ISSUE TITLE
Fux Supporters rows

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/foundation.btcpayserver.org#11]
I've added the new supporter in #10 but wasn't aware of the approach we want to take when it comes to rows. 

I kinda lean towards 2 rows, but leaving it up to styling masters @vswee and @dennisreimann to decide and implement as my css skills suck. 😄 

![Capture](https://user-images.githubusercontent.com/36959754/91171140-4ac67300-e6da-11ea-88e5-ef9f1e380c56.PNG)

**Comment by dennisreimann** [comment]
Will do this right away :)
