### ISSUE TITLE
Improve the past supporters page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/foundation.btcpayserver.org#12]
Inevitably, certain supporters may not longer be able to support the foundation. While we cannot display them on the main site/repo/blog/server, we can give them credits on the `past supporters` page of some sort.

Opening this issue to discuss how to handle the `past-supporters` page and if anyone is aware of similar examples. 

Such page should be linked from the foundation.btcpayserver.org and perhaps from the main repository.

I've came across these 
- https://www.colalife.org/support/supporters/#past
- https://www.kidsinspire.org.uk/past-corporate-supporters

**Comment by britttttk** [comment]
@pavlenex I think colalife link is a good example. For the description possibly we could describe what was developed/worked on during that time. Although this might be a bit misleading and seem to attribute that work to that particular donor..

For that reason we might want to do something like the second one. We could also ask them for a blurb like a quote of some sort as to why they made the donation to us for us to display on our site. 

What do you think?

**Comment by britttttk** [comment]
ping @Zaxounette are you aware of any examples of this sort of thing?

**Comment by Zaxounette** [comment]
I don't like either of the two examples Pav stated.

colalife is too detailed for what we do IMHO. And i'd add the logos of the supporters on what kidsinspire did.

----

**What I propose for this:**

Don't make a new page for past supporters. 
Simply move them down. Just under the google form, as to not distract from the actual workflow of the page, yet still visible near it.

Then define who is moved to that section:
* Supporters that have explicitly expressed their end of support for whatever reason and after a defined date
* Supporters that haven't contributed in the last XYZ days/months/year

This proposal then becomes a matter of CTRL+X / CTRL+V to the lower section. Low maintenance, low initial creation time.

**Comment by pavlenex** [comment]
@britttttk For starters it should really just be a simple page with logos of supporters (we have 2 for now). I wouldn't add any text for now, though it can be a good idea to build on later on to expand the page. The reason for separate page is that it should be easily linked from other sources and also not to prominently display supporters who are no longer supporting us, as that would be unfair to the current supporters.

Maintenance isn't the issue here it's not something that should be maintained regularly and there's no need to display them on the front page imo.

**Comment by Zaxounette** [comment]
I understand the fact of a new page being easily linkable.
I would have no objection for a new simple page with just page title, 3 word sentence and past supporter logos.

**Comment by pavlenex** [comment]
We probably want to improve this 😄 

![Screenshot 2021-07-30 at 17 52 53](https://user-images.githubusercontent.com/36959754/127679155-31054519-e383-4b81-858b-57d7b6d75ad8.png)

**Comment by dennisreimann** [comment]
@pavlenex Done with c868eab27491501779afa0a283118f294ef49daf.
