### ISSUE TITLE
Website re-design to fit design guidelines

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/foundation.btcpayserver.org#8]
I propose we re-design the foundation website to fit the newly created design guidelines. Whoever is willing to tackle this, feel free to discuss it with community on Mattermost chat.btcpayserver.org.

I don't think a major overhaul is needed, for starters we can just make sure the re-designed site is consistent with design.btcpayserver.org

Unsure if there's something more in codebase we should restructure @Kukks?

**Comment by Kukks** [comment]
I can tackle this if you like. Need something basic to clear my head

**Comment by pavlenex** [comment]
Haha 😆 - sure!

**Comment by pavlenex** [comment]
Done in #9
